### ISSUE TITLE
Sample Project Broken

### ISSUE THREAD

**Issue by ShootMe** [MattThorson/Strawberry#6]
Seems the sample was broken a while back. Any chance to get it working again? Wanted to take a look at it and play around :)

**Comment by MaddyThorson** [comment]
I'm doing some rewrites and hopefully will have it working again soon :)

**Comment by MaddyThorson** [comment]
Okay it works again! The engine still needs a ton of work and the sample game is very simple, but it works :)

**Comment by ShootMe** [comment]
Awesome thanks!
